const mongoose = require("mongoose");

const userSchema = mongoose.Schema(
  {
    ID: { type: String },
    Source: { type: String },
    TMC: { type: String },
    Severity: { type: Number, enum: [1, 2, 3] },
    Start_Time: { type: Date },
    End_Time: { type: Date },
    Start_Lat: { type: Number },
    Start_Lng: { type: Number },
    End_Lat: { type: Number },
    End_Lng: { type: Number },
    Distance: { type: Number },
    Description: { type: String },
    Number: { type: String },
    Street: { type: String },
    Side: { type: String, enum: ["Left", "Right"] },
    City: { type: String },
    County: { type: String },
    State: { type: String },
    Zipcode: { type: String },
    Country: { type: String },
    Timezone: { type: String },
    Airport_Code: { type: String },
    Weather_Timestamp: { type: String },
    Temperature: { type: Number },
    Wind_Chill: { type: Number },
    Humidity: { type: Number },
    Pressure: { type: Number },
    Visibility: { type: String },
    Wind_Direction: { type: Number },
    Wind_Speed: { type: Number },
    Precipitation: { type: String },
    Weather_Condition: { type: String },
    Amenity: { type: Boolean },
    Bump: { type: Boolean },
    Crossing: { type: Boolean },
    Give_Way: { type: Boolean },
    Junction: { type: Boolean },
    No_Exit: { type: Boolean },
    Railway: { type: Boolean },
    Roundabout: { type: Boolean },
    Station: { type: Boolean },
    Stop: { type: Boolean },
    Traffic_Calming: { type: Boolean },
    Traffic_Signal: { type: Boolean },
    Turning_Loop: { type: String },
    Sunrise_Sunset: { type: String },
    Civil_Twilight: { type: String },
    Nautical_Twilight: { type: String },
    Astronomical_Twilight: { type: String },
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

module.exports = userSchema;
