const mongoose = require("mongoose");

const accidentSchema = mongoose.Schema({
  ID: { type: String },
  Source: { type: String },
  TMC: { type: String },
  Severity: { type: Number, enum: [1, 2, 3] },
  Start_Time: { type: Date },
  End_Time: { type: Date },
  Start_Lat: { type: Number },
  Start_Lng: { type: Number },
  End_Lat: { type: Number },
  End_Lng: { type: Number },
  Distance: { type: Number },
  Description: { type: String },
  Number: { type: String },
  Street: { type: String },
  Side: { type: String, enum: ["L", "R"] },
  City: { type: String },
  County: { type: String },
  State: { type: String },
  Zipcode: { type: String },
  Country: { type: String },
  Timezone: { type: String },
  Airport_Code: { type: String },
  Weather_Timestamp: { type: String },
  Temperature: { type: Number },
  Wind_Chill: { type: Number },
  Humidity: { type: Number },
  Pressure: { type: Number },
  Visibility: { type: String },
  Wind_Direction: { type: String },
  Wind_Speed: { type: Number },
  Precipitation: { type: String },
  Weather_Condition: { type: String },
  Amenity: { type: String },
  Bump: { type: String },
  Crossing: { type: String },
  Give_Way: { type: String },
  Junction: { type: String },
  No_Exit: { type: String },
  Railway: { type: String },
  Roundabout: { type: String },
  Station: { type: String },
  Stop: { type: String },
  Traffic_Calming: { type: String },
  Traffic_Signal: { type: String },
  Turning_Loop: { type: String },
  Sunrise_Sunset: { type: String },
  Civil_Twilight: { type: String },
  Nautical_Twilight: { type: String },
  Astronomical_Twilight: { type: String },
});

module.exports = accidentSchema;
